### ISSUE TITLE
Can't use plugin

### ISSUE THREAD

**Issue by Phatcat** [ArthurGareginyan/my-custom-functions#3]
I can't activate the plugin; not even a fresh clean copy of the plugin will install.

getting this error;
> Parse error: syntax error, unexpected '.', expecting end of file in /customers/7/a/d/bauerskincare.dk/httpd.www/wp-content/plugins/my-custom-functions/inc/php/functional.php(85) : eval()'d code on line 34

**Comment by ArthurGareginyan** [comment]
This plugin has a built-in functions for checking the custom PHP code for syntax errors, duplicate functions names, and etc. But plugin is not perfect, so there are times when the entered custom PHP code causes an error and white screen. This is due to the fact that your custom PHP code has a syntax error that this plugin could not detect. When this happens with you just do the following and all will be fine.

1.  Via FTP, go to the plugin folder (in 'wp-content/plugins/my-custom-functions/').
2.  Rename the "START" file to "STOP". This will stop the execution of your custom code.
3.  Return to the WordPress Admin Panel and activate the plugin. Now it should activate without problems.
4.  Go to the plugin settings page and edit/fix your custom PHP code that you entered before the crash.
5.  Rename the "STOP" file to "START" and you're done!

I'm already working on the function to automatically stop the plugin for cases when this plugin could not detect the error, and this caused the inaccessibility of the website.

**Comment by Phatcat** [comment]
Thank you so much for the speedy response. Also great plugin! (It was indeed some of my bad code crippling my whole site forcing me to manually remove the plugin and trying to re-apply it, yeah.. lead me here.)

**Comment by ArthurGareginyan** [comment]
You're welcome!

Thank you for choosing my WordPress plugin :)

Have a good day!

**Comment by Phatcat** [comment]
your solution worked perfectly. Thank you very much for the support. You can consider this issue resolved :+1:
